name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-package:
    name: Check Package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.0.0

      - name: Install Dependencies
        run: uv sync --locked

      - name: Check Formatting
        uses: dprint/check@v2.3

      - name: Check C++ Formatting
        run: find . -name '*.cpp' -exec clang-format --dry-run --Werror {} +

      - name: Check Lint
        run: uv run ruff check

      - name: Build Source Distribution
        run: uv build --sdist

  build-package:
    name: Build Package
    needs: check-package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2022
          - windows-11-arm
          - macos-13
          - macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.0.0

      - name: Install Dependencies
        run: uv sync

      - name: Test Package
        run: uv run pytest -v --cov

      - name: Build Wheels
        run: uv run cibuildwheel --output-dir wheelhouse

      - name: Upload Wheels
        uses: actions/upload-artifact@v4.6.2
        with:
          name: wheelhouse-${{ matrix.os }}
          path: ./wheelhouse/*.whl
